# -*- coding: utf-8 -*-
import scrapy

from .. import settings
from ..items import CCSpiderItem

CURRENCY_IDS = {
    '1ST': 'firstblood',
    'ACT': 'achain',
    'ADA': 'cardano',
    'ADT': 'adtoken',
    'ADX': 'adx-net',
    'AE': 'aeternity',
    'AEON': 'aeon',
    'AGRS': 'agoras-tokens',
    'AION': 'aion',
    'ALIS': 'alis',
    'AMB': 'amber',
    'AMP': 'synereo',
    'ANT': 'aragon',
    'ARDR': 'ardor',
    'ARK': 'ark',
    'AST': 'airswap',
    'ATB': 'atbcoin',
    'ATM': 'attention-token-of-media',
    'AVT': 'aventus',
    'BAT': 'basic-attention-token',
    'BAY': 'bitbay',
    'BBR': 'boolberry',
    'BCC': 'bitconnect',
    'BCH': 'bitcoin-cash',
    'BCN': 'bytecoin-bcn',
    'BCO': 'bridgecoin',
    'BCPT': 'blockmason',
    'BITB': 'bitbean',
    'BITCNY': 'bitcny',
    'BITUSD': 'bitusd',
    'BLK': 'blackcoin',
    'BLOCK': 'blocknet',
    'BLUE': 'ethereum-blue',
    'BNB': 'binance-coin',
    'BNT': 'bancor',
    'BOT': 'bodhi',
    'BQ': 'bitqy',
    'BSD': 'bitsend',
    'BTC': 'bitcoin',
    'BTCD': 'bitcoindark',
    'BTG': 'bitcoin-gold',
    'BTM': 'bytom',
    'BTS': 'bitshares',
    'BTX': 'bitcore',
    'BURST': 'burst',
    'CDT': 'coindash',
    'CFI': 'cofound-it',
    'CLAM': 'clams',
    'CLOAK': 'cloakcoin',
    'CND': 'cindicator',
    'CNX': 'cryptonex',
    'COB': 'cobinhood',
    'COVAL': 'circuits-of-value',
    'CRW': 'crown',
    'CSNO': 'bitdice',
    'CTR': 'centra',
    'CVC': 'civic',
    'DASH': 'dash',
    'DATA': 'streamr-datacoin',
    'DCN': 'dentacoin',
    'DCR': 'decred',
    'DCT': 'decent',
    'DENT': 'dent',
    'DGB': 'digibyte',
    'DGD': 'digixdao',
    'DICE': 'etheroll',
    'DIME': 'dimecoin',
    'DLT': 'agrello-delta',
    'DMD': 'diamond',
    'DNT': 'district0x',
    'DOGE': 'dogecoin',
    'DPY': 'delphy',
    'DRGN': 'dragonchain',
    'DRT': 'domraider',
    'DTB': 'databits',
    'EDG': 'edgeless',
    'EDO': 'eidoo',
    'EMC': 'emercoin',
    'EMC2': 'einsteinium',
    'EMV': 'ethereum-movie-venture',
    'ENG': 'enigma-project',
    'ENJ': 'enjin-coin',
    'EOS': 'eos',
    'ETC': 'ethereum-classic',
    'ETH': 'ethereum',
    'ETHOS': 'ethos',
    'ETN': 'electroneum',
    'ETP': 'metaverse',
    'EVX': 'everex',
    'EXP': 'expanse',
    'FAIR': 'faircoin',
    'FCT': 'factom',
    'FLDC': 'foldingcoin',
    'FLO': 'florincoin',
    'FRST': 'firstcoin',
    'FTC': 'feathercoin',
    'FUEL': 'etherparty',
    'FUN': 'funfair',
    'GAM': 'gambit',
    'GAME': 'gamecredits',
    'GAS': 'gas',
    'GBYTE': 'byteball',
    'GCR': 'global-currency-reserve',
    'GNO': 'gnosis-gno',
    'GNT': 'golem-network-tokens',
    'GOLOS': 'golos',
    'GRC': 'gridcoin',
    'GRID': 'grid',
    'GRS': 'groestlcoin',
    'GUP': 'guppy',
    'GVT': 'genesis-vision',
    'GXS': 'gxshares',
    'HMQ': 'humaniq',
    'HSR': 'hshare',
    'HST': 'decision-token',
    'HVN': 'hive',
    'ICN': 'iconomi',
    'ICOS': 'icos',
    'INCNT': 'incent',
    'INK': 'ink',
    'IOC': 'iocoin',
    'ION': 'ion',
    'IXT': 'ixledger',
    'JINN': 'jinn',
    'KCS': 'kucoin-shares',
    'KICK': 'kickico',
    'KIN': 'kin',
    'KMD': 'komodo',
    'KNC': 'kyber-network',
    'LBC': 'library-credit',
    'LEND': 'ethlend',
    'LEO': 'leocoin',
    'LINK': 'chainlink',
    'LKK': 'lykke',
    'LMC': 'lomocoin',
    'LRC': 'loopring',
    'LSK': 'lisk',
    'LTC': 'litecoin',
    'LUN': 'lunyr',
    'MAID': 'maidsafecoin',
    'MANA': 'decentraland',
    'MCO': 'monaco',
    'MDA': 'moeda-loyalty-points',
    'MER': 'mercury',
    'MGO': 'mobilego',
    'MIOTA': 'iota',
    'MLN': 'melon',
    'MNX': 'minexcoin',
    'MOD': 'modum',
    'MONA': 'monacoin',
    'MOON': 'mooncoin',
    'MSP': 'mothership',
    'MTH': 'monetha',
    'MTL': 'metal',
    'MUE': 'monetaryunit',
    'MUSIC': 'musicoin',
    'MYST': 'mysterium',
    'NAV': 'nav-coin',
    'NEBL': 'neblio',
    'NEO': 'neo',
    'NEOS': 'neoscoin',
    'NET': 'nimiq',
    'NLC2': 'nolimitcoin',
    'NLG': 'gulden',
    'NMC': 'namecoin',
    'NMR': 'numeraire',
    'NULS': 'nuls',
    'NVST': 'nvo',
    'NXC': 'nexium',
    'NXS': 'nexus',
    'NXT': 'nxt',
    'OBITS': 'obits',
    'OCT': 'oraclechain',
    'ODN': 'obsidian',
    'OK': 'okcash',
    'OMG': 'omisego',
    'OMNI': 'omni',
    'OST': 'simple-token',
    'OTN': 'open-trading-network',
    'PART': 'particl',
    'PASC': 'pascal-coin',
    'PAY': 'tenx',
    'PEPECASH': 'pepe-cash',
    'PHR': 'phore',
    'PINK': 'pinkcoin',
    'PIVX': 'pivx',
    'PLBT': 'polybius',
    'PLR': 'pillar',
    'POE': 'poet',
    'POSW': 'posw-coin',
    'POT': 'potcoin',
    'POWR': 'power-ledger',
    'PPC': 'peercoin',
    'PPP': 'paypie',
    'PPT': 'populous',
    'PPY': 'peerplays-ppy',
    'PRE': 'presearch',
    'PRG': 'paragon',
    'PST': 'primas',
    'PTOY': 'patientory',
    'PURA': 'pura',
    'QASH': 'qash',
    'QAU': 'quantum',
    'QRL': 'quantum-resistant-ledger',
    'QSP': 'quantstamp',
    'QTUM': 'qtum',
    'R': 'revain',
    'RADS': 'radium',
    'RBY': 'rubycoin',
    'RCN': 'ripio-credit-network',
    'RDD': 'reddcoin',
    'RDN': 'raiden-network-token',
    'REP': 'augur',
    'REQ': 'request-network',
    'RHOC': 'rchain',
    'RISE': 'rise',
    'RLC': 'rlc',
    'RMC': 'russian-mining-coin',
    'RPX': 'red-pulse',
    'SALT': 'salt',
    'SAN': 'santiment',
    'SBD': 'steem-dollars',
    'SC': 'siacoin',
    'SHIFT': 'shift',
    'SIB': 'sibcoin',
    'SKY': 'skycoin',
    'SLR': 'solarcoin',
    'SLS': 'salus',
    'SMART': 'smartcash',
    'SNC': 'suncontract',
    'SNGLS': 'singulardtv',
    'SNM': 'sonm',
    'SNT': 'status',
    'SPANK': 'spankchain',
    'STEEM': 'steem',
    'STORJ': 'storj',
    'STRAT': 'stratis',
    'STX': 'stox',
    'SUB': 'substratum',
    'SWT': 'swarm-city',
    'SYS': 'syscoin',
    'TAAS': 'taas',
    'TCC': 'the-champcoin',
    'THC': 'hempcoin',
    'TIPS': 'fedoracoin',
    'TIX': 'blocktix',
    'TKN': 'tokencard',
    'TNB': 'time-new-bank',
    'TNT': 'tierion',
    'TRIG': 'triggers',
    'TRST': 'trust',
    'TRX': 'tron',
    'TX': 'transfercoin',
    'UBQ': 'ubiq',
    'UKG': 'unikoin-gold',
    'UNITY': 'supernet-unity',
    'UNO': 'unobtanium',
    'USDT': 'tether',
    'VEE': 'blockv',
    'VERI': 'veritaseum',
    'VET': 'vechain',
    'VIA': 'viacoin',
    'VIB': 'viberate',
    'VOX': 'voxels',
    'VRC': 'vericoin',
    'VTC': 'vertcoin',
    'WABI': 'wabi',
    'WAVES': 'waves',
    'WCT': 'waves-community-token',
    'WGR': 'wagerr',
    'WINGS': 'wings',
    'WTC': 'walton',
    'XAS': 'asch',
    'XAUR': 'xaurum',
    'XBY': 'xtrabytes',
    'XCP': 'counterparty',
    'XDN': 'digitalnote',
    'XEL': 'elastic',
    'XEM': 'nem',
    'XLM': 'stellar',
    'XMR': 'monero',
    'XMY': 'myriad',
    'XP': 'xp',
    'XRB': 'raiblocks',
    'XRL': 'rialto',
    'XRP': 'ripple',
    'XSH': 'shield-xsh',
    'XSPEC': 'spectrecoin',
    'XST': 'stealthcoin',
    'XUC': 'exchange-union',
    'XVC': 'vcash',
    'XVG': 'verge',
    'XWC': 'whitecoin',
    'XZC': 'zcoin',
    'YOYOW': 'yoyow',
    'ZEC': 'zcash',
    'ZEN': 'zencash',
    'ZNY': 'bitzeny',
    'ZRX': '0x',
    'ZSC': 'zeusshield'
}


class CoinMarketCapSpider(scrapy.Spider):
    name = 'cmc'
    allowed_domains = ['coinmarketcap.com']
    start_urls = ['https://coinmarketcap.com/']
    custom_settings = {
        # cf. https://doc.scrapy.org/en/latest/topics/feed-exports.html#feed-export-fields
        'FEED_EXPORT_FIELDS': ['symbol', 'date', 'open', 'high', 'low', 'close', 'volume', 'market_cap'],
    }

    def __init__(self, symbol=None, *args, **kwargs):
        super(CoinMarketCapSpider, self).__init__(*args, **kwargs)
        self.symbol = symbol
        self.start_urls = [
            'https://coinmarketcap.com/currencies/{name}/historical-data/?start={start}&end={end}'.format(
                name=CURRENCY_IDS[symbol],
                start=settings.START_DATE,
                end=settings.END_DATE,
            ),
        ]

    def parse(self, response):
        for sel in response.css('table tbody tr'):
            item = CCSpiderItem()
            item['symbol'] = self.symbol
            item['date'] = sel.css('td:nth-child(1)::text').extract_first()
            item['open'] = sel.css('td:nth-child(2)::text').extract_first()
            item['high'] = sel.css('td:nth-child(3)::text').extract_first()
            item['low'] = sel.css('td:nth-child(4)::text').extract_first()
            item['close'] = sel.css('td:nth-child(5)::text').extract_first()
            item['volume'] = sel.css('td:nth-child(6)::text').extract_first()
            item['market_cap'] = sel.css('td:nth-child(7)::text').extract_first()
            yield item
